/**
 * DB 스키마 (Postgres). 앱이 처음 DB 에 붙을 때 아직 적용하지 않은 것만 순서대로 적용한다 (Database.migrate).
 * 이미 적용한 마이그레이션은 절대 고치지 말고, 바꿀 게 있으면 새 항목을 뒤에 추가한다.
 */
export const MIGRATIONS: { name: string; sql: string }[] = [
  {
    name: '001_init',
    sql: /* sql */ `
CREATE TABLE users (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email               VARCHAR(100) NOT NULL,
    password            VARCHAR(100) NOT NULL,
    nickname            VARCHAR(20)  NOT NULL,
    -- 2단계 인증: 켜면 로그인할 때 이메일로 받은 인증번호를 한 번 더 입력한다
    two_factor_enabled  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_nickname UNIQUE (nickname)
);

-- 채널. slug(고리)는 주소(/c/{slug})에 쓰이고 바꿀 수 없다. 기본 채널은 운영 채널이라 주인이 없다.
CREATE TABLE channels (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug          VARCHAR(30)   NOT NULL,
    name          VARCHAR(20)   NOT NULL,
    description   VARCHAR(2000) NOT NULL DEFAULT '',
    owner_id      INTEGER       REFERENCES users (id),
    -- 카운터는 원자적 UPDATE 로만 바꾼다
    post_count    INTEGER       NOT NULL DEFAULT 0,
    member_count  INTEGER       NOT NULL DEFAULT 0,
    -- 프로필 이미지 버전: 0 보다 크면 이미지가 있다. 지우면 부호만 바꿔(-n) 다음 이미지가 옛 캐시와 겹치지 않게 한다
    icon_version  INTEGER       NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uk_channels_slug UNIQUE (slug),
    CONSTRAINT uk_channels_name UNIQUE (name)
);
-- 인기 채널: ORDER BY post_count DESC, id
CREATE INDEX idx_channels_popular ON channels (post_count DESC, id);

-- 프로필 이미지 바이트는 목록 쿼리가 무거워지지 않게 따로 둔다
CREATE TABLE channel_icons (
    channel_id    INTEGER     PRIMARY KEY REFERENCES channels (id) ON DELETE CASCADE,
    content_type  VARCHAR(20) NOT NULL,
    data          BYTEA       NOT NULL
);

-- 채널 안 카테고리 (공지사항, 소설 …). owner_only 면 운영진만 글을 쓸 수 있다
CREATE TABLE channel_categories (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id  INTEGER     NOT NULL REFERENCES channels (id) ON DELETE CASCADE,
    name        VARCHAR(20) NOT NULL,
    position    INTEGER     NOT NULL,
    owner_only  BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_channel_categories_name UNIQUE (channel_id, name)
);
CREATE INDEX idx_channel_categories_position ON channel_categories (channel_id, position);

-- 채널 가입 + 운영진 역할: OWNER 소유자 · ADMIN 관리자 · MANAGER 매니저 · MEMBER 일반 멤버
CREATE TABLE channel_members (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id  INTEGER     NOT NULL REFERENCES channels (id) ON DELETE CASCADE,
    user_id     INTEGER     NOT NULL REFERENCES users (id),
    role        VARCHAR(10) NOT NULL DEFAULT 'MEMBER',
    joined_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_channel_members UNIQUE (channel_id, user_id)
);
-- 내가 가입한 채널: WHERE user_id = ? ORDER BY id DESC
CREATE INDEX idx_channel_members_user ON channel_members (user_id, id);

-- 채널 북마크 (가입과 별개)
CREATE TABLE channel_bookmarks (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id  INTEGER     NOT NULL REFERENCES channels (id) ON DELETE CASCADE,
    user_id     INTEGER     NOT NULL REFERENCES users (id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_channel_bookmarks UNIQUE (channel_id, user_id)
);
CREATE INDEX idx_channel_bookmarks_user ON channel_bookmarks (user_id, id);

CREATE TABLE posts (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id      INTEGER      NOT NULL REFERENCES users (id),
    channel_id     INTEGER      NOT NULL REFERENCES channels (id),
    -- 카테고리를 지우면 글은 남고 카테고리만 비워진다
    category_id    INTEGER      REFERENCES channel_categories (id) ON DELETE SET NULL,
    title          VARCHAR(100) NOT NULL,
    -- 마크다운 원문. 렌더링(과 XSS 방지 sanitize)은 클라이언트에서 한다
    content        TEXT         NOT NULL,
    -- 목록에서 본문(TEXT)을 읽지 않도록 미리 잘라 둔, 마크다운 기호를 뺀 미리보기
    excerpt        VARCHAR(160) NOT NULL,
    view_count     INTEGER      NOT NULL DEFAULT 0,
    like_count     INTEGER      NOT NULL DEFAULT 0,
    comment_count  INTEGER      NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);
-- 키셋 페이지네이션: WHERE <조건> AND id < ? ORDER BY id DESC
CREATE INDEX idx_posts_channel_id ON posts (channel_id, id);
CREATE INDEX idx_posts_category_id ON posts (category_id, id);
CREATE INDEX idx_posts_author_id ON posts (author_id, id);
-- 인기글: 최근 N일 범위
CREATE INDEX idx_posts_created_at ON posts (created_at);

CREATE TABLE comments (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id     INTEGER       NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    author_id   INTEGER       NOT NULL REFERENCES users (id),
    content     VARCHAR(1000) NOT NULL,
    like_count  INTEGER       NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now()
);
CREATE INDEX idx_comments_post_id ON comments (post_id, id);
-- 베스트 댓글: WHERE post_id = ? AND like_count >= ? ORDER BY like_count DESC
CREATE INDEX idx_comments_post_like ON comments (post_id, like_count);

CREATE TABLE post_likes (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id     INTEGER     NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    user_id     INTEGER     NOT NULL REFERENCES users (id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_post_likes UNIQUE (post_id, user_id)
);

CREATE TABLE comment_likes (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id  INTEGER     NOT NULL REFERENCES comments (id) ON DELETE CASCADE,
    user_id     INTEGER     NOT NULL REFERENCES users (id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_comment_likes UNIQUE (comment_id, user_id)
);

-- 이메일 인증번호 (회원가입 · 2단계 인증 켜기 · 2단계 인증 로그인). 번호는 SHA-256 해시로만 저장한다
CREATE TABLE email_codes (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(100) NOT NULL,
    purpose     VARCHAR(20)  NOT NULL,
    code_hash   CHAR(64)     NOT NULL,
    -- 2단계 인증 로그인에서 비밀번호를 확인한 사람만 번호를 입력할 수 있게 하는 일회용 토큰
    challenge   VARCHAR(64),
    user_id     INTEGER,
    attempts    INTEGER      NOT NULL DEFAULT 0,
    expires_at  TIMESTAMPTZ  NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_email_codes_challenge UNIQUE (challenge)
);
CREATE INDEX idx_email_codes_lookup ON email_codes (email, purpose, id);

-- 기본 채널 (운영 채널, 주인 없음)
INSERT INTO channels (slug, name, description) VALUES
    ('free', '자유', '무엇이든 자유롭게 이야기해요'),
    ('question', '질문', '궁금한 건 무엇이든 물어보세요'),
    ('info', '정보', '알아두면 좋은 정보를 나눠요'),
    ('daily', '일상', '오늘 하루는 어땠나요?');
`,
  },
  {
    // 글 본문 이미지. 편집(자르기·크기 등)은 주소 뒤 #설정으로 하므로 올린 원본은 바뀌지 않는다
    name: '002_images',
    sql: `
CREATE TABLE images (
    id            VARCHAR(32)  PRIMARY KEY,
    owner_id      INTEGER      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content_type  VARCHAR(20)  NOT NULL,
    data          BYTEA        NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_images_owner ON images (owner_id, created_at);
`,
  },
  {
    // 로그인한 기기(세션). 토큰에 세션 id 를 넣고 요청마다 확인해서, 로그아웃하면 그 기기의 토큰만 바로 못 쓰게 한다
    name: '003_sessions',
    sql: `
CREATE TABLE sessions (
    id            VARCHAR(32)  PRIMARY KEY,
    user_id       INTEGER      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    user_agent    VARCHAR(300) NOT NULL DEFAULT '',
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_used_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    expires_at    TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_sessions_user ON sessions (user_id, last_used_at);
`,
  },
  {
    // 글을 본 사람. 같은 계정(비로그인은 같은 브라우저·앱)이 다시 보거나 새로고침해도 조회수는 한 번만 오른다
    name: '004_post_views',
    sql: `
CREATE TABLE post_views (
    post_id     INTEGER      NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    viewer      VARCHAR(64)  NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    PRIMARY KEY (post_id, viewer)
);
`,
  },
  {
    // 이미지가 없는 채널 프로필의 색 (CHANNEL_COLORS 의 번호). 예전 채널은 NULL → 고리로 정한 색
    name: '005_channel_color',
    sql: `ALTER TABLE channels ADD COLUMN color SMALLINT;`,
  },
  {
    // 비공개 채널(초대 코드로만 가입) · 만 19세 이상 채널/카테고리 · 나이 확인용 생년월일
    name: '006_private_adult',
    sql: `
ALTER TABLE channels ADD COLUMN visibility VARCHAR(10) NOT NULL DEFAULT 'public';
ALTER TABLE channels ADD COLUMN invite_code VARCHAR(16);
ALTER TABLE channels ADD COLUMN adult BOOLEAN NOT NULL DEFAULT FALSE;
CREATE UNIQUE INDEX uk_channels_invite_code ON channels (invite_code);
ALTER TABLE channel_categories ADD COLUMN adult BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN birth_date DATE;
`,
  },
  {
    // 프로필 사진 · 배너(기본 배너는 무료, 커스텀 배너는 포인트로 연다) · 포인트와 그 기록
    name: '007_profile',
    sql: `
ALTER TABLE users ADD COLUMN avatar_id VARCHAR(32) REFERENCES images (id) ON DELETE SET NULL;
ALTER TABLE users ADD COLUMN banner VARCHAR(48);
ALTER TABLE users ADD COLUMN points INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN custom_banner BOOLEAN NOT NULL DEFAULT FALSE;
CREATE TABLE point_logs (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    delta       INTEGER      NOT NULL,
    reason      VARCHAR(40)  NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_point_logs_user ON point_logs (user_id, id);
`,
  },
  {
    // 댓글의 답글(한 단계) · 수정 시각
    name: '008_comment_replies',
    sql: `
ALTER TABLE comments ADD COLUMN parent_id INTEGER REFERENCES comments (id) ON DELETE CASCADE;
ALTER TABLE comments ADD COLUMN updated_at TIMESTAMPTZ;
CREATE INDEX idx_comments_parent ON comments (parent_id, id);
`,
  },
  {
    // 바깥(API · 주소)에 보이는 사용자 id. 순서대로 늘어나는 내부 id 대신 UUID 를 쓴다 (몇 번째 가입자인지 드러나지 않게)
    name: '009_user_uid',
    sql: `
ALTER TABLE users ADD COLUMN uid UUID NOT NULL DEFAULT gen_random_uuid();
CREATE UNIQUE INDEX uk_users_uid ON users (uid);
`,
  },
  {
    // 포인트 적립(출석 · 공감 받기) · 배지(도전과제) · 친구 초대
    name: '010_rewards',
    sql: `
ALTER TABLE users ADD COLUMN invite_code VARCHAR(8) NOT NULL DEFAULT upper(substr(md5(random()::text), 1, 8));
CREATE UNIQUE INDEX uk_users_invite_code ON users (invite_code);
ALTER TABLE users ADD COLUMN invited_by INTEGER REFERENCES users (id) ON DELETE SET NULL;
CREATE TABLE attendance (
    user_id  INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    day      DATE    NOT NULL,
    PRIMARY KEY (user_id, day)
);
-- 같은 사람이 같은 글에 공감을 눌렀다 취소했다 해도 포인트는 한 번만 (글이 지워져도 남겨 둔다)
CREATE TABLE like_rewards (
    post_id   INTEGER NOT NULL,
    liker_id  INTEGER NOT NULL,
    PRIMARY KEY (post_id, liker_id)
);
CREATE TABLE user_badges (
    user_id     INTEGER     NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    code        VARCHAR(30) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, code)
);
`,
  },
  {
    // 이미 있는 채널도 운영진 전용 카테고리를 일반 카테고리보다 위로 (각 무리 안의 순서는 그대로)
    name: '011_staff_categories_first',
    sql: `
UPDATE channel_categories c SET position = o.rn - 1
FROM (SELECT id, row_number() OVER (PARTITION BY channel_id ORDER BY owner_only DESC, position, id) AS rn FROM channel_categories) o
WHERE c.id = o.id;
`,
  },
  {
    // '내 사진 배너' 를 '커스텀 배너' 로 부르기로 해서 지난 포인트 내역도 같은 이름으로
    name: '012_custom_banner_wording',
    sql: `UPDATE point_logs SET reason = '커스텀 배너 열기' WHERE reason = '내 사진 배너 열기';`,
  },
  {
    // 소셜 로그인(Google · Kakao · Naver): 소셜 계정 하나는 사용자 하나에 이어진다
    name: '013_user_identities',
    sql: `
CREATE TABLE user_identities (
    provider          VARCHAR(10)  NOT NULL,
    provider_user_id  VARCHAR(100) NOT NULL,
    user_id           INTEGER      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    PRIMARY KEY (provider, provider_user_id)
);
CREATE INDEX idx_user_identities_user ON user_identities (user_id);
`,
  },
];
